/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/axChPVkoUqa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"

export function Dashboard() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
     
     
     
     
      <header className="px-2 lg:px-6 h-14 flex items-center fixed top-0 w-full text-white  shadow-md border-b backdrop-blur-xl ring-offset-purple-500 rounded-lg ">
        <Link href="/" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6 font-extrabold" />
          <span className="sr-only">Acme Blog</span>
        </Link>
          <nav className="ml-auto flex gap-4 sm:gap-6"> 
          <Link href="/" className="text-md  font-bold hover:underline underline-offset-4" prefetch={false}>
            Home
          </Link>
          <Link href="/blog" className="text-md font-bold hover:underline underline-offset-4" prefetch={false}>
            Articles
          </Link>
          <Link href="/doc" className="text-md font-bold hover:underline underline-offset-4" prefetch={false}>
            Tutorials
          </Link>
          
          <Link href="/about" className="text-sm font-bold hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
        </nav>
      </header>




      
    <div className=" items-center flex min-h-screen flex-col ">
      <main className=" gap-7 ">
        <section className="w-full py-6 sm:py-12 md:py-16 lg:py-20 xl:py-24 ">
          <div className="container px-4 md:px-6 items-center justify-between">

            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-6 bg-slate-500 rounded-md  text-black">
              <Tabs defaultValue="articles ">
                <TabsList className="flex gap-4 sm:gap-6">
                  <TabsTrigger  value="1">1st Year</TabsTrigger>
                  <TabsTrigger value="2">2nd Year</TabsTrigger>
                  <TabsTrigger value="3">3rd Year</TabsTrigger>
                  <TabsTrigger value="4">4th Year</TabsTrigger>
                </TabsList>
              </Tabs>
              <div className="flex gap-2 mt-4 sm:mt-0">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline" size="sm">
                      Course <ChevronDownIcon className="w-4 h-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="start">
                    <DropdownMenuItem>Cse</DropdownMenuItem>
                    <DropdownMenuItem>IT</DropdownMenuItem>
                    <DropdownMenuItem>ECE</DropdownMenuItem>
                    <DropdownMenuItem>CSE(A.I)</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline" size="sm">
                      Subject <ChevronDownIcon className="w-4 h-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="start">
                    <DropdownMenuItem>Math</DropdownMenuItem>
                    <DropdownMenuItem>Physics</DropdownMenuItem>
                    <DropdownMenuItem>Chemistry</DropdownMenuItem>
                    <DropdownMenuItem>English</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline" size="sm">
                      Material <ChevronDownIcon className="w-4 h-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="start">
                    <DropdownMenuItem>E-book</DropdownMenuItem>
                    <DropdownMenuItem>Youtube Playlist</DropdownMenuItem>
                    <DropdownMenuItem>Notes</DropdownMenuItem>
                    <DropdownMenuItem>Question Bank</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline" size="sm">
                      Content type <ChevronDownIcon className="w-4 h-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="start">
                    <DropdownMenuItem> Free 🆓</DropdownMenuItem>
                    <DropdownMenuItem>Paid 💵</DropdownMenuItem>
                   
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>



            <div className="grid  gap-7   sm:grid-cols-4 md:gap-3  justify-between content-between ">
              
              
              <Card className="bg-secondary  ">
                <CardHeader>
                  <CardTitle>
                    <Link href="#" className="text-secondary-foreground" prefetch={false}>
                      The Future of Web Development
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-secondary-foreground">
                    Exploring the latest trends and technologies shaping the web development landscape.
                  </CardDescription>
                </CardHeader>
              
                <CardFooter>
                  <div className="flex items-center gap-2 text-sm text-secondary-foreground">
                    <CalendarIcon className="w-4 h-4" />
                    <span>June 1, 2023</span>
                  </div>
                </CardFooter>
              </Card>
              <Card className="bg-secondary  ">
                <CardHeader>
                  <CardTitle>
                    <Link href="#" className="text-secondary-foreground" prefetch={false}>
                      The Future of Web Development
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-secondary-foreground">
                    Exploring the latest trends and technologies shaping the web development landscape.
                  </CardDescription>
                </CardHeader>
              
                <CardFooter>
                  <div className="flex items-center gap-2 text-sm text-secondary-foreground">
                    <CalendarIcon className="w-4 h-4" />
                    <span>June 1, 2023</span>
                  </div>
                </CardFooter>
              </Card><Card className="bg-secondary  ">
                <CardHeader>
                  <CardTitle>
                    <Link href="#" className="text-secondary-foreground" prefetch={false}>
                      The Future of Web Development
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-secondary-foreground">
                    Exploring the latest trends and technologies shaping the web development landscape.
                  </CardDescription>
                </CardHeader>
              
                <CardFooter>
                  <div className="flex items-center gap-2 text-sm text-secondary-foreground">
                    <CalendarIcon className="w-4 h-4" />
                    <span>June 1, 2023</span>
                  </div>
                </CardFooter>
              </Card><Card className="bg-secondary  ">
                <CardHeader>
                  <CardTitle>
                    <Link href="#" className="text-secondary-foreground" prefetch={false}>
                      The Future of Web Development
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-secondary-foreground">
                    Exploring the latest trends and technologies shaping the web development landscape.
                  </CardDescription>
                </CardHeader>
              
                <CardFooter>
                  <div className="flex items-center gap-2 text-sm text-secondary-foreground">
                    <CalendarIcon className="w-4 h-4" />
                    <span>June 1, 2023</span>
                  </div>
                </CardFooter>
              </Card><Card className="bg-secondary  ">
                <CardHeader>
                  <CardTitle>
                    <Link href="#" className="text-secondary-foreground" prefetch={false}>
                      The Future of Web Development
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-secondary-foreground">
                    Exploring the latest trends and technologies shaping the web development landscape.
                  </CardDescription>
                </CardHeader>
              
                <CardFooter>
                  <div className="flex items-center gap-2 text-sm text-secondary-foreground">
                    <CalendarIcon className="w-4 h-4" />
                    <span>June 1, 2023</span>
                  </div>
                </CardFooter>
              </Card><Card className="bg-secondary  ">
                <CardHeader>
                  <CardTitle>
                    <Link href="#" className="text-secondary-foreground" prefetch={false}>
                      The Future of Web Development
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-secondary-foreground">
                    Exploring the latest trends and technologies shaping the web development landscape.
                  </CardDescription>
                </CardHeader>
              
                <CardFooter>
                  <div className="flex items-center gap-2 text-sm text-secondary-foreground">
                    <CalendarIcon className="w-4 h-4" />
                    <span>June 1, 2023</span>
                  </div>
                </CardFooter>
              </Card><Card className="bg-secondary  ">
                <CardHeader>
                  <CardTitle>
                    <Link href="#" className="text-secondary-foreground" prefetch={false}>
                      The Future of Web Development
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-secondary-foreground">
                    Exploring the latest trends and technologies shaping the web development landscape.
                  </CardDescription>
                </CardHeader>
              
                <CardFooter>
                  <div className="flex items-center gap-2 text-sm text-secondary-foreground">
                    <CalendarIcon className="w-4 h-4" />
                    <span>June 1, 2023</span>
                  </div>
                </CardFooter>
              </Card><Card className="bg-secondary  ">
                <CardHeader>
                  <CardTitle>
                    <Link href="#" className="text-secondary-foreground" prefetch={false}>
                      The Future of Web Development
                    </Link>
                  </CardTitle>
                  <CardDescription className="text-secondary-foreground">
                    Exploring the latest trends and technologies shaping the web development landscape.
                  </CardDescription>
                </CardHeader>
              
                <CardFooter>
                  <div className="flex items-center gap-2 text-sm text-secondary-foreground">
                    <CalendarIcon className="w-4 h-4" />
                    <span>June 1, 2023</span>
                  </div>
                </CardFooter>
              </Card>
              
             
            </div>
           
          </div>
        </section>
      </main>
    </div>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-slate-100 text-black">
        <p className="text-xs text-muted-foreground text-black font-bold">&copy; 2024 Emakaut. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6" />
      </footer>
    </div>
  )
}

function CalendarIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ChevronDownIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function MountainIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
